# Generated by Django 3.0.1 on 2020-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
