# Generated by Django 3.0.1 on 2020-01-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0015_auto_20200113_2129'),
        ('complaint', '0004_auto_20200114_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_student.student'),
        ),
    ]
