# Generated by Django 3.0.1 on 2020-01-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20200114_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cats',
        ),
    ]
