# Generated by Django 3.0.1 on 2020-01-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0015_auto_20200113_2129'),
        ('complaint', '0007_remove_complaint_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_student.student'),
        ),
    ]
