# Generated by Django 3.0.1 on 2020-01-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_complaint_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='approved_tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
