# Generated by Django 3.0.1 on 2020-01-12 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0014_student_requested_approved_tag'),
        ('complaint', '0011_complaint_approved_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='users_student.student'),
            preserve_default=False,
        ),
    ]
