# Generated by Django 3.0.1 on 2020-01-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_auto_20200112_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
    ]
