# Generated by Django 2.2.5 on 2020-01-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0003_auto_20200113_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='gender',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='ongoing_complaints',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='solved_complaints',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
