# Generated by Django 2.2.7 on 2020-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0004_auto_20200114_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='rejected_complaints',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
