# Generated by Django 3.0.1 on 2020-01-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0011_auto_20191228_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/IMG_1520.JPG', upload_to='profile_picture/'),
        ),
    ]
