# Generated by Django 3.0.1 on 2020-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0012_auto_20200111_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='requested_tag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
