# Generated by Django 3.0.1 on 2020-01-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0013_student_requested_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='requested_approved_tag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
